In [2]:
import pandas as pd
import glob

In [3]:
files = glob.glob("/Users/aysesudekarabal/data-cleaning/e-commerce/e-commerce-dirty-datas/*.csv")

In [4]:
dfs = []
for f in files:
    df = pd.read_csv(f)
    print(df.columns)
    dfs.append(df)
combined = pd.concat(dfs,ignore_index = True)

Index(['goods-title-link--jump', 'goods-title-link--jump href', 'price',
       'discount', 'selling_proposition', 'goods-title-link'],
      dtype='str')
Index(['product-locatelabels-img src', 'color-count', 'goods-title-link',
       'rank-title', 'rank-sub', 'price', 'discount', 'selling_proposition'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href',
       'selling_proposition', 'price', 'discount', 'color-count',
       'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'color-count', 'selling_proposition', 'discount',
       'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='str')
Index(['goods-title-link', 'rank-title', 'rank-sub', 'price',
       'selling_proposition', 'discount'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href',
       'selling_proposition', 'price', 'discount', 'rank-title', 'rank-sub',
       'color-count', 'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition', 'color-count',
       'goods-title-link'],
      dtype='str')
Index(['color-count', 'blackfridaybelts-bg src', 'blackfridaybelts-content',
       'goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='str')
Index(['color-count', 'goods-title-link--jump', 'goods-title-link--jump href',
       'selling_proposition', 'price', 'discount', 'rank-title', 'rank-sub',
       'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href',
       'selling_proposition', 'price', 'discount', 'color-count', 'rank-title',
       'rank-sub', 'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'selling_proposition', 'discount',
       'goods-title-link'],
      dtype='str')
Index(['color-count', 'goods-title-link--jump', 'goods-title-link--jump href',
       'rank-title', 'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'selling_proposition', 'discount',
       'goods-title-link'],
      dtype='str')
Index(['color-count', 'goods-title-link--jump', 'goods-title-link--jump href',
       'rank-title', 'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='str')
Index(['color-count', 'goods-title-link--jump', 'goods-title-link--jump href',
       'price', 'rank-title', 'rank-sub', 'discount', 'goods-title-link'],
      dtype='str')
Index(['goods-title-link--jump', 'goods-title-link--jump href',
       'selling_proposition', 'price', 'blackfridaybelts-bg src',
       'blackfridaybelts-content', 'rank-title', 'rank-sub', 'discount',
       'color-count', 'goods-title-link'],
      dtype='str')
Index(['rank-title', 'rank-sub', 'price', 'selling_proposition', 'discount',
       'goods-title-link'],
      dtype='str')
Index(['color-count', 'goods-title-link--jump', 'goods-title-link--jump href',
       'rank-title', 'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='str')
Index(['color-count', 'goods-title-link', 'selling_proposition', 'price',
       'discount', 'rank-title', 'rank-sub'],
      dtype='str')

In [5]:
combined.isna().sum()

goods-title-link--jump          81441
goods-title-link--jump href     81441
price                               2
discount                        27128
selling_proposition             27741
goods-title-link                  678
product-locatelabels-img src    78483
color-count                     62362
rank-title                      67500
rank-sub                        67500
blackfridaybelts-bg src         78314
blackfridaybelts-content        78314
dtype: int64

In [6]:
len(combined)

82105

In [7]:
combined[combined["price"].isna() == True]

,goods-title-link--jump,goods-title-link--jump href,price,discount,selling_proposition,goods-title-link,product-locatelabels-img src,color-count,rank-title,rank-sub,blackfridaybelts-bg src,blackfridaybelts-content
64356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
combined.drop([64356,82004], inplace = True)

In [9]:
combined[combined["goods-title-link"].isna() == True]

,goods-title-link--jump,goods-title-link--jump href,price,discount,selling_proposition,goods-title-link,product-locatelabels-img src,color-count,rank-title,rank-sub,blackfridaybelts-bg src,blackfridaybelts-content
0,"1pc/2PCS Car Cup Coaster, Bling Cup Holder Ins...",https://us.shein.com/1pc-2PCS-Car-Cup-Coaster-...,$0.68,-60%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jesus The Way Truth Life Sticker For Car Windo...,https://us.shein.com/Jesus-The-Way-Truth-Life-...,$1.60,-20%,500+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2PC Car Rearview Mirror Rain Eyebrow And Rain ...,https://us.shein.com/2PC-Car-Rearview-Mirror-R...,$1.60,NaN,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"2pcs Car Rearview Mirror Rainproof Film, High-...",https://us.shein.com/2pcs-Car-Rearview-Mirror-...,$0.93,-34%,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2pcs Multifunctional Car Hook,https://us.shein.com/2pcs-Multifunctional-Car-...,$1.12,-20%,1.9k+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
75869,New Leopard Print Bowknot Simple Pointed Toe F...,https://us.shein.com/New-Leopard-Print-Bowknot...,$9.50,-17%,10+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75870,SHEIN SHUZIA Women's Hollow Out Breathable Shoes,https://us.shein.com/SHEIN-SHUZIA-Women-s-Holl...,$18.81,-1%,NaN,NaN,NaN,4.0,#1 Best Seller,In Khaki Women Clogs,NaN,NaN
75871,Women Summer Square Open Toe Slides Backless M...,https://us.shein.com/Women-Summer-Square-Open-...,$22.14,-10%,50+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75872,"Men's Casual Sports Sneakers, Non-slip White S...",https://us.shein.com/Men-s-Casual-Sports-Sneak...,$18.43,-27%,NaN,NaN,NaN,5.0,#3 Best Sellers,in Men Casual Shoes,NaN,NaN
75873,Women Criss Cross Sculptural Heeled Ankle Stra...,https://us.shein.com/Women-Criss-Cross-Sculptu...,$20.40,-21%,NaN,NaN,NaN,9.0,#4 Best Seller,In Gold Women Heeled Sandals,NaN,NaN

In [10]:
combined[(combined["goods-title-link"].isna() == False) & (combined["goods-title-link--jump"].isna() == False)]

Empty DataFrame
Columns: [goods-title-link--jump, goods-title-link--jump href, price, discount, selling_proposition, goods-title-link, product-locatelabels-img src, color-count, rank-title, rank-sub, blackfridaybelts-bg src, blackfridaybelts-content]
Index: []

In [11]:
combined["goods-title-link--jump"]= combined["goods-title-link--jump"].fillna(combined["goods-title-link"])

In [12]:
combined["goods-title-link--jump"].isna().sum()

np.int64(12)

In [13]:
combined[combined["goods-title-link--jump"].isna()]

,goods-title-link--jump,goods-title-link--jump href,price,discount,selling_proposition,goods-title-link,product-locatelabels-img src,color-count,rank-title,rank-sub,blackfridaybelts-bg src,blackfridaybelts-content
72259,NaN,NaN,$2.90,NaN,NaN,NaN,NaN,NaN,#6 Best Sellers,in Kids Drawing & Painting Supplies,NaN,NaN
72260,NaN,NaN,$2.40,NaN,600+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72261,NaN,NaN,$3.80,NaN,1.2k+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72262,NaN,NaN,$1.20,NaN,NaN,NaN,NaN,NaN,#2 Best Sellers,in Musical Instruments & Accessories,NaN,NaN
72263,NaN,NaN,$2.31,-54%,500+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72264,NaN,NaN,$6.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72265,NaN,NaN,$0.56,-67%,NaN,NaN,NaN,NaN,#2 Best Sellers,in Dice Games,NaN,NaN
72266,NaN,NaN,$4.45,-16%,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72267,NaN,NaN,$2.90,NaN,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72268,NaN,NaN,$2.96,-15%,NaN,NaN,NaN,NaN,#3 Best Sellers,in Kids Math Manipulatives,NaN,NaN
72269,NaN,NaN,$0.90,-65%,NaN,NaN,NaN,NaN,#1 Best Sellers,in Gaming Top Toys,NaN,NaN
72270,NaN,NaN,$2.90,NaN,20+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
combined["goods-title-link--jump"]= combined["goods-title-link--jump"].fillna("Unknown")

In [15]:
combined = combined.rename(columns= {"goods-title-link--jump":"title"})

In [16]:
combined = combined.drop(columns = ["goods-title-link"])

In [17]:
combined.head()

,title,goods-title-link--jump href,price,discount,selling_proposition,product-locatelabels-img src,color-count,rank-title,rank-sub,blackfridaybelts-bg src,blackfridaybelts-content
0,"1pc/2PCS Car Cup Coaster, Bling Cup Holder Ins...",https://us.shein.com/1pc-2PCS-Car-Cup-Coaster-...,$0.68,-60%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jesus The Way Truth Life Sticker For Car Windo...,https://us.shein.com/Jesus-The-Way-Truth-Life-...,$1.60,-20%,500+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN
2,2PC Car Rearview Mirror Rain Eyebrow And Rain ...,https://us.shein.com/2PC-Car-Rearview-Mirror-R...,$1.60,NaN,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN
3,"2pcs Car Rearview Mirror Rainproof Film, High-...",https://us.shein.com/2pcs-Car-Rearview-Mirror-...,$0.93,-34%,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN
4,2pcs Multifunctional Car Hook,https://us.shein.com/2pcs-Multifunctional-Car-...,$1.12,-20%,1.9k+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
combined["price"] = combined["price"].str.replace('$',' ')

In [19]:
combined["discount"] = combined["discount"].str.replace('%', ' ')

In [20]:
combined.head()

,title,goods-title-link--jump href,price,discount,selling_proposition,product-locatelabels-img src,color-count,rank-title,rank-sub,blackfridaybelts-bg src,blackfridaybelts-content
0,"1pc/2PCS Car Cup Coaster, Bling Cup Holder Ins...",https://us.shein.com/1pc-2PCS-Car-Cup-Coaster-...,0.68,-60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jesus The Way Truth Life Sticker For Car Windo...,https://us.shein.com/Jesus-The-Way-Truth-Life-...,1.60,-20,500+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN
2,2PC Car Rearview Mirror Rain Eyebrow And Rain ...,https://us.shein.com/2PC-Car-Rearview-Mirror-R...,1.60,NaN,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN
3,"2pcs Car Rearview Mirror Rainproof Film, High-...",https://us.shein.com/2pcs-Car-Rearview-Mirror-...,0.93,-34,200+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN
4,2pcs Multifunctional Car Hook,https://us.shein.com/2pcs-Multifunctional-Car-...,1.12,-20,1.9k+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
combined["price"] = pd.to_numeric(combined["price"],errors = "coerce")

In [22]:
combined["discount"] = pd.to_numeric(combined["discount"],errors = "coerce")
combined["color-count"] = pd.to_numeric(combined["color-count"],errors = "coerce")

In [23]:
combined.dtypes

title                               str
goods-title-link--jump href         str
price                           float64
discount                        float64
selling_proposition                 str
product-locatelabels-img src        str
color-count                     float64
rank-title                          str
rank-sub                            str
blackfridaybelts-bg src             str
blackfridaybelts-content            str
dtype: object

In [24]:
combined.duplicated(subset = ["title","price"]).sum()

np.int64(8630)

In [25]:
combined = combined.drop_duplicates(subset = ["title","price"])

In [26]:
# 1. Sayıyı ve ardından gelen 'k' veya 'm' harfini ayır
extracted = combined["selling_proposition"].str.extract(r'([\d.]+)([kKmM]?)')

# 2. Sayısal kısmı dönüştür
nums = pd.to_numeric(extracted[0], errors='coerce')

# 3. Harflere göre çarpanları belirle (k = 1.000, m = 1.000.000)
multipliers = extracted[1].str.lower().map({'k': 1000, 'm': 1000000}).fillna(1)

# 4. Çarpıp yeni sütuna yaz
combined["sold_over_count"] = nums * multipliers

In [39]:
combined.tail()

,title,goods-title-link--jump href,price,discount,selling_proposition,product-locatelabels-img src,color-count,rank-title,rank-sub,blackfridaybelts-bg src,blackfridaybelts-content,sold_over_count
82100,Manfinity Men's Vacation Zebra-Print Drawstrin...,NaN,11.39,-7.0,NaN,NaN,NaN,#9 Best Seller,in Graphic Men Swimwear,NaN,NaN,NaN
82101,GAWX Men's Casual Color-Block Slogan Printed T...,NaN,13.09,-14.0,10+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,10.0
82102,Manfinity Hypemode Men Pocket Front Drawstring...,NaN,14.29,-23.0,NaN,NaN,NaN,#8 Best Seller,in Drawstring Men Shirts,NaN,NaN,NaN
82103,DAZY Men Patched Pocket Denim Shirt,NaN,25.39,-7.0,NaN,NaN,NaN,#6 Best Seller,in Long Sleeve Men Denim Shirts,NaN,NaN,NaN
82104,Manfinity Hypemode Men's Loose Fit Pleated Fol...,NaN,20.19,-7.0,600+ sold recently,NaN,4.0,NaN,NaN,NaN,NaN,600.0

In [31]:
combined[combined['selling_proposition'].isna()]['sold_over_count'].notna().sum()

np.int64(0)

In [36]:
(combined["price"]<=0).sum()

np.int64(0)

In [35]:
(combined["discount"]>100).sum()

np.int64(0)

In [46]:
combined["rank-number"] = pd.to_numeric(combined["rank-title"].str.extract(r'([\d.]+)')[0])

In [47]:
combined.tail()

,title,goods-title-link--jump href,price,discount,selling_proposition,product-locatelabels-img src,color-count,rank-title,rank-sub,blackfridaybelts-bg src,blackfridaybelts-content,sold_over_count,rank-number
82100,Manfinity Men's Vacation Zebra-Print Drawstrin...,NaN,11.39,-7.0,NaN,NaN,NaN,#9 Best Seller,in Graphic Men Swimwear,NaN,NaN,NaN,9.0
82101,GAWX Men's Casual Color-Block Slogan Printed T...,NaN,13.09,-14.0,10+ sold recently,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
82102,Manfinity Hypemode Men Pocket Front Drawstring...,NaN,14.29,-23.0,NaN,NaN,NaN,#8 Best Seller,in Drawstring Men Shirts,NaN,NaN,NaN,8.0
82103,DAZY Men Patched Pocket Denim Shirt,NaN,25.39,-7.0,NaN,NaN,NaN,#6 Best Seller,in Long Sleeve Men Denim Shirts,NaN,NaN,NaN,6.0
82104,Manfinity Hypemode Men's Loose Fit Pleated Fol...,NaN,20.19,-7.0,600+ sold recently,NaN,4.0,NaN,NaN,NaN,NaN,600.0,NaN

In [48]:
combined.to_csv("e-commerce_all_cleaned.csv",index = False)