In [2]:
import pandas as pd

In [3]:
dp = pd.read_csv("dirty_cafe_sales.csv")

In [4]:
dp.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
dp.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
dp.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

In [7]:
for x in dp.columns:
    print(dp[x].isnull().sum())

0
333
138
179
173
2579
3265
159

In [9]:
print((dp["Quantity"].isnull() & dp["Price Per Unit"].isnull()).sum())
print((dp["Quantity"].isnull() & dp["Total Spent"].isnull()).sum())
print((dp["Price Per Unit"].isnull() & dp["Total Spent"].isnull()).sum())

1
3
2

In [10]:
dp.groupby("Item")["Price Per Unit"].unique()

Item
Cake                               [3.0, nan, UNKNOWN, ERROR]
Coffee                             [2.0, nan, ERROR, UNKNOWN]
Cookie                             [1.0, UNKNOWN, nan, ERROR]
ERROR       [1.5, 3.0, 5.0, nan, 4.0, 2.0, 1.0, UNKNOWN, E...
Juice                              [3.0, nan, UNKNOWN, ERROR]
Salad                              [5.0, ERROR, UNKNOWN, nan]
Sandwich                           [4.0, nan, ERROR, UNKNOWN]
Smoothie                           [4.0, nan, UNKNOWN, ERROR]
Tea                                [1.5, nan, ERROR, UNKNOWN]
UNKNOWN     [3.0, 1.0, 5.0, 4.0, 1.5, 2.0, nan, UNKNOWN, E...
Name: Price Per Unit, dtype: object

In [11]:
import numpy as np

In [12]:
dp = dp.replace(["UNKNOWN","ERROR"], np.nan)

In [13]:
dp.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [14]:
dp.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [15]:
dp.groupby("Item")["Price Per Unit"].unique()

Item
Cake        [3.0, nan]
Coffee      [2.0, nan]
Cookie      [1.0, nan]
Juice       [3.0, nan]
Salad       [5.0, nan]
Sandwich    [4.0, nan]
Smoothie    [4.0, nan]
Tea         [1.5, nan]
Name: Price Per Unit, dtype: object

In [16]:
type(dp["Price Per Unit"])

pandas.Series

In [17]:
dp["Price Per Unit"] = pd.to_numeric(dp["Price Per Unit"], errors="coerce")

In [18]:
price_dict = dp.groupby("Item")["Price Per Unit"].mean()

In [20]:
dp["Price Per Unit"] = dp["Price Per Unit"].fillna(dp["Item"].map(price_dict))

In [21]:
dp.tail(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9980,TXN_6796890,Tea,4,1.5,6.0,NaN,NaN,2023-08-24
9981,TXN_4583012,NaN,5,4.0,20.0,Digital Wallet,NaN,2023-02-27
9982,TXN_8567525,Cookie,2,1.0,2.0,NaN,Takeaway,2023-12-30
9983,TXN_9226047,Smoothie,3,4.0,12.0,Cash,NaN,NaN
9984,TXN_3142496,Smoothie,NaN,4.0,4.0,Cash,Takeaway,2023-07-27
9985,TXN_3297457,Cake,2,3.0,6.0,NaN,NaN,2023-01-03
9986,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9987,TXN_1784478,Juice,5,3.0,15.0,Cash,NaN,2023-07-31
9988,TXN_9594133,Cake,5,3.0,NaN,NaN,NaN,NaN
9989,TXN_1741685,Juice,5,3.0,15.0,Cash,NaN,2023-08-18
9990,TXN_1538510,Coffee,5,2.0,10.0,Digital Wallet,NaN,2023-05-22
9991,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4,4.0,16.0,NaN,In-store,2023-07-05
9993,TXN_4766549,Smoothie,2,4.0,NaN,Cash,NaN,2023-10-20
9994,TXN_7851634,NaN,4,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [22]:
dp["Price Per Unit"].isnull().sum()

np.int64(54)

In [23]:
dp[dp["Price Per Unit"].isnull()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
118,TXN_4633784,NaN,5,NaN,15.0,NaN,In-store,2023-02-06
151,TXN_4031509,NaN,4,NaN,16.0,Credit Card,Takeaway,2023-01-04
289,TXN_3495950,NaN,4,NaN,6.0,Credit Card,In-store,2023-02-19
334,TXN_2523298,NaN,4,NaN,6.0,NaN,In-store,2023-03-25
550,TXN_4186681,NaN,4,NaN,6.0,Digital Wallet,NaN,2023-05-24
750,TXN_5787508,NaN,3,NaN,9.0,Credit Card,Takeaway,2023-07-23
818,TXN_7940202,NaN,1,NaN,4.0,Digital Wallet,NaN,2023-07-23
1154,TXN_2473090,NaN,2,NaN,3.0,Credit Card,In-store,2023-03-03
1337,TXN_5031214,NaN,5,NaN,5.0,NaN,Takeaway,2023-07-29
1377,TXN_8396271,NaN,2,NaN,2.0,NaN,NaN,2023-09-12
1589,TXN_5245399,NaN,5,NaN,10.0,NaN,NaN,2023-12-25
1761,TXN_3611851,NaN,4,NaN,NaN,Credit Card,NaN,2023-02-09
1786,TXN_1923349,NaN,4,NaN,6.0,NaN,NaN,2023-07-06
2002,TXN_5206049,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-24
2227,TXN_3200203,NaN,2,NaN,8.0,NaN,NaN,2023-12-04
2289,TXN_7524977,NaN,4,NaN,NaN,NaN,NaN,2023-12-09
2596,TXN_4844386,NaN,5,NaN,15.0,Credit Card,In-store,2023-10-28
2610,TXN_8266689,NaN,5,NaN,15.0,Cash,In-store,2023-12-03
2962,TXN_9702662,NaN,4,NaN,16.0,NaN,Takeaway,2023-07-10
3013,TXN_1842697,NaN,5,NaN,15.0,NaN,NaN,2023-10-25
3404,TXN_7797231,NaN,5,NaN,10.0,Digital Wallet,NaN,2023-05-05
3434,TXN_6457997,NaN,1,NaN,4.0,Credit Card,NaN,2023-12-12
3666,TXN_8616276,NaN,2,NaN,3.0,Digital Wallet,Takeaway,2023-07-22
3739,TXN_4849180,NaN,5,NaN,15.0,Credit Card,In-store,2023-10-14
3779,TXN_7376255,NaN,NaN,NaN,25.0,NaN,In-store,2023-05-27
3900,TXN_5093855,NaN,4,NaN,6.0,Cash,Takeaway,2023-11-23
4092,TXN_1840897,NaN,1,NaN,5.0,NaN,NaN,2023-06-03
4152,TXN_9646000,NaN,2,NaN,NaN,NaN,In-store,2023-12-14
4621,TXN_7844352,NaN,2,NaN,6.0,Credit Card,NaN,2023-07-26
5039,TXN_9514452,NaN,5,NaN,10.0,Credit Card,Takeaway,2023-07-29
5891,TXN_9618962,NaN,3,NaN,6.0,Credit Card,Takeaway,2023-11-08
5991,TXN_2913107,NaN,4,NaN,8.0,NaN,In-store,2023-05-20
6177,TXN_3232279,NaN,4,NaN,16.0,NaN,Takeaway,2023-05-30
6345,TXN_4208919,NaN,3,NaN,12.0,NaN,Takeaway,2023-05-30
6429,TXN_2536573,NaN,2,NaN,8.0,Cash,In-store,2023-06-24
6849,TXN_7928378,NaN,3,NaN,12.0,Cash,NaN,2023-07-04
7478,TXN_9710982,NaN,4,NaN,16.0,NaN,NaN,2023-03-03
7597,TXN_1082717,NaN,NaN,NaN,9.0,Digital Wallet,In-store,2023-12-13
8129,TXN_8384699,NaN,3,NaN,15.0,NaN,In-store,2023-12-16
8458,TXN_7595907,NaN,5,NaN,15.0,NaN,In-store,2023-04-24
8463,TXN_2150872,NaN,5,NaN,15.0,Cash,Takeaway,2023-03-18
8817,TXN_8365530,NaN,4,NaN,16.0,NaN,Takeaway,2023-03-10
8959,TXN_3803063,NaN,4,NaN,12.0,Credit Card,Takeaway,2023-11-23
9174,TXN_5935353,NaN,2,NaN,8.0,Credit Card,NaN,2023-05-01
9234,TXN_8918253,NaN,3,NaN,12.0,Digital Wallet,NaN,2023-09-07
9382,TXN_4255580,NaN,1,NaN,3.0,Cash,NaN,NaN
9425,TXN_2065683,NaN,3,NaN,6.0,NaN,NaN,2023-09-21
9454,TXN_1637131,NaN,4,NaN,6.0,Cash,NaN,NaN
9673,TXN_2480808,NaN,1,NaN,4.0,Credit Card,NaN,2023-03-30
9717,TXN_3334632,NaN,1,NaN,2.0,Credit Card,Takeaway,2023-11-20
9764,TXN_1688292,NaN,3,NaN,9.0,Credit Card,In-store,NaN
9819,TXN_1208561,NaN,NaN,NaN,20.0,Credit Card,NaN,2023-08-19
9820,TXN_8751702,NaN,5,NaN,15.0,Cash,NaN,2023-02-13
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02

In [24]:
dp[dp["Price Per Unit"].isnull()][["Item", "Quantity", "Total Spent"]]

     Item Quantity Total Spent
118   NaN        5        15.0
151   NaN        4        16.0
289   NaN        4         6.0
334   NaN        4         6.0
550   NaN        4         6.0
750   NaN        3         9.0
818   NaN        1         4.0
1154  NaN        2         3.0
1337  NaN        5         5.0
1377  NaN        2         2.0
1589  NaN        5        10.0
1761  NaN        4         NaN
1786  NaN        4         6.0
2002  NaN        3         3.0
2227  NaN        2         8.0
2289  NaN        4         NaN
2596  NaN        5        15.0
2610  NaN        5        15.0
2962  NaN        4        16.0
3013  NaN        5        15.0
3404  NaN        5        10.0
3434  NaN        1         4.0
3666  NaN        2         3.0
3739  NaN        5        15.0
3779  NaN      NaN        25.0
3900  NaN        4         6.0
4092  NaN        1         5.0
4152  NaN        2         NaN
4621  NaN        2         6.0
5039  NaN        5        10.0
5891  NaN        3         6.0
5991  NaN        4         8.0
6177  NaN        4        16.0
6345  NaN        3        12.0
6429  NaN        2         8.0
6849  NaN        3        12.0
7478  NaN        4        16.0
7597  NaN      NaN         9.0
8129  NaN        3        15.0
8458  NaN        5        15.0
8463  NaN        5        15.0
8817  NaN        4        16.0
8959  NaN        4        12.0
9174  NaN        2         8.0
9234  NaN        3        12.0
9382  NaN        1         3.0
9425  NaN        3         6.0
9454  NaN        4         6.0
9673  NaN        1         4.0
9717  NaN        1         2.0
9764  NaN        3         9.0
9819  NaN      NaN        20.0
9820  NaN        5        15.0
9996  NaN        3         3.0

In [25]:
dp = dp.drop([3779,7597,9819,4152,1761])

In [26]:
dp["Price Per Unit"].isnull().sum()

np.int64(49)

In [27]:
dp["Quantity"] = pd.to_numeric(dp["Quantity"], errors = "coerce")

In [28]:

dp["Total Spent"] = pd.to_numeric(dp["Total Spent"], errors = "coerce")

In [29]:
dp["Price Per Unit"] = dp["Price Per Unit"].fillna(dp["Total Spent"] / dp["Quantity"])

In [30]:
dp["Price Per Unit"].isnull().sum()

np.int64(1)

In [31]:
dp.isnull().sum()

Transaction ID         0
Item                 964
Quantity             476
Price Per Unit         1
Total Spent          500
Payment Method      3176
Location            3959
Transaction Date     460
dtype: int64

In [32]:
dp["Quantity"] = dp["Price Per Unit"].fillna(dp["Total Spent"] / dp["Price Per Unit"])

In [33]:
dp["Total Spent"] = dp["Price Per Unit"].fillna(dp["Quantity"] * dp["Price Per Unit"])

In [35]:
dp[dp["Price Per Unit"].isnull()][["Item", "Quantity", "Total Spent"]]

     Item  Quantity  Total Spent
2289  NaN       NaN          NaN

In [36]:
dp = dp.drop(2289)

In [37]:
dp.isnull().sum()

Transaction ID         0
Item                 963
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      3175
Location            3958
Transaction Date     460
dtype: int64

In [38]:
price_dict.value_counts()

Price Per Unit
3.0    2
4.0    2
2.0    1
1.0    1
5.0    1
1.5    1
Name: count, dtype: int64

In [39]:
dp[dp["Item"].isnull()]["Price Per Unit"].value_counts()

Price Per Unit
3.0    247
4.0    227
2.0    126
5.0    124
1.0    121
1.5    118
Name: count, dtype: int64

In [41]:
dict_reversed = {v: k for k,v in price_dict.items()}

In [44]:
price_dict.value_counts()

Price Per Unit
3.0    2
4.0    2
2.0    1
1.0    1
5.0    1
1.5    1
Name: count, dtype: int64

In [48]:
price_counts = price_dict.value_counts()

In [49]:
dict_reversed = {v: k for k,v in price_dict.items() if price_counts[v] == 1}

In [50]:
print(dict_reversed)

{2.0: 'Coffee', 1.0: 'Cookie', 5.0: 'Salad', 1.5: 'Tea'}

In [52]:
dp["Item"] = dp["Item"].fillna(dp["Price Per Unit"].map(dict_reversed))

In [53]:
dp.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,2.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,3.0,3.0,3.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,1.0,1.0,1.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,5.0,5.0,5.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,2.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,4.0,4.0,4.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3.0,3.0,3.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,4.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,3.0,3.0,3.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,4.0,4.0,4.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,5.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,4.0,4.0,4.0,Credit Card,Takeaway,NaN
12,TXN_7619095,Sandwich,4.0,4.0,4.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,1.0,1.0,1.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,Tea,1.5,1.5,1.5,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,5.0,5.0,5.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,4.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,3.0,3.0,3.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,3.0,3.0,3.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,3.0,3.0,3.0,Cash,Takeaway,2023-01-15

In [54]:
dp["Item"].isnull().sum()

np.int64(474)

In [55]:
dp["Item"] = dp["Item"].fillna("Unknown")

In [57]:
dp.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      3175
Location            3958
Transaction Date     460
dtype: int64

In [58]:
dp.sort_values("Transaction ID")

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2987,TXN_1000555,Tea,1.5,1.5,1.5,Credit Card,In-store,2023-10-19
115,TXN_1001832,Salad,5.0,5.0,5.0,Cash,Takeaway,NaN
418,TXN_1002457,Cookie,1.0,1.0,1.0,Digital Wallet,Takeaway,2023-09-29
3417,TXN_1003246,Juice,3.0,3.0,3.0,NaN,NaN,2023-02-15
4366,TXN_1004184,Smoothie,4.0,4.0,4.0,Credit Card,In-store,2023-05-18
...,...,...,...,...,...,...,...,...
1389,TXN_9996968,Sandwich,4.0,4.0,4.0,Cash,In-store,2023-10-14
7964,TXN_9997263,Cookie,1.0,1.0,1.0,NaN,NaN,2023-03-05
4304,TXN_9997620,Cookie,1.0,1.0,1.0,Cash,NaN,2023-12-11
98,TXN_9999113,Juice,3.0,3.0,3.0,Cash,Takeaway,2023-05-27
5037,TXN_9999124,Juice,3.0,3.0,3.0,Digital Wallet,Takeaway,NaN

In [59]:
dp.groupby("Location")["Item"].value_counts()

Location  Item
In-store  Salad       406
          Cookie      373
          Sandwich    370
          Tea         369
          Juice       361
          Coffee      352
          Smoothie    322
          Cake        321
          Unknown     140
Takeaway  Cookie      402
          Coffee      396
          Salad       378
          Tea         368
          Sandwich    345
          Cake        343
          Juice       341
          Smoothie    304
          Unknown     145
Name: count, dtype: int64

In [60]:
dp.groupby("Payment Method")["Item"].value_counts()

Payment Method  Item
Cash            Salad       316
                Cake        276
                Cookie      274
                Coffee      266
                Juice       266
                Tea         264
                Sandwich    253
                Smoothie    236
                Unknown     107
Credit Card     Salad       306
                Cookie      279
                Juice       276
                Coffee      275
                Tea         261
                Sandwich    256
                Cake        253
                Smoothie    252
                Unknown     113
Digital Wallet  Coffee      295
                Cookie      291
                Juice       285
                Tea         279
                Salad       274
                Sandwich    255
                Smoothie    255
                Cake        246
                Unknown     110
Name: count, dtype: int64

In [61]:
dp.groupby("Payment Method")["Location"].value_counts()

Payment Method  Location
Cash            In-store    702
                Takeaway    664
Credit Card     In-store    681
                Takeaway    669
Digital Wallet  Takeaway    744
                In-store    694
Name: count, dtype: int64

In [62]:
dp.groupby("Location")["Item"].value_counts()

Location  Item
In-store  Salad       406
          Cookie      373
          Sandwich    370
          Tea         369
          Juice       361
          Coffee      352
          Smoothie    322
          Cake        321
          Unknown     140
Takeaway  Cookie      402
          Coffee      396
          Salad       378
          Tea         368
          Sandwich    345
          Cake        343
          Juice       341
          Smoothie    304
          Unknown     145
Name: count, dtype: int64

In [63]:
dp["Location"] = dp["Location"].fillna("Unknown")

In [64]:
dp["Payment Method"] = dp["Payment Method"].fillna("Unknown")

In [65]:
dp.tail(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9980,TXN_6796890,Tea,1.5,1.5,1.5,Unknown,Unknown,2023-08-24
9981,TXN_4583012,Unknown,4.0,4.0,4.0,Digital Wallet,Unknown,2023-02-27
9982,TXN_8567525,Cookie,1.0,1.0,1.0,Unknown,Takeaway,2023-12-30
9983,TXN_9226047,Smoothie,4.0,4.0,4.0,Cash,Unknown,NaN
9984,TXN_3142496,Smoothie,4.0,4.0,4.0,Cash,Takeaway,2023-07-27
9985,TXN_3297457,Cake,3.0,3.0,3.0,Unknown,Unknown,2023-01-03
9986,TXN_2858441,Sandwich,4.0,4.0,4.0,Credit Card,In-store,2023-12-14
9987,TXN_1784478,Juice,3.0,3.0,3.0,Cash,Unknown,2023-07-31
9988,TXN_9594133,Cake,3.0,3.0,3.0,Unknown,Unknown,NaN
9989,TXN_1741685,Juice,3.0,3.0,3.0,Cash,Unknown,2023-08-18
9990,TXN_1538510,Coffee,2.0,2.0,2.0,Digital Wallet,Unknown,2023-05-22
9991,TXN_3897619,Sandwich,4.0,4.0,4.0,Cash,Takeaway,2023-02-24
9992,TXN_2739140,Smoothie,4.0,4.0,4.0,Unknown,In-store,2023-07-05
9993,TXN_4766549,Smoothie,4.0,4.0,4.0,Cash,Unknown,2023-10-20
9994,TXN_7851634,Unknown,4.0,4.0,4.0,Unknown,Unknown,2023-01-08
9995,TXN_7672686,Coffee,2.0,2.0,2.0,Unknown,Unknown,2023-08-30
9996,TXN_9659401,Cookie,1.0,1.0,1.0,Digital Wallet,Unknown,2023-06-02
9997,TXN_5255387,Coffee,2.0,2.0,2.0,Digital Wallet,Unknown,2023-03-02
9998,TXN_7695629,Cookie,1.0,1.0,1.0,Digital Wallet,Unknown,2023-12-02
9999,TXN_6170729,Sandwich,4.0,4.0,4.0,Cash,In-store,2023-11-07

In [66]:
dp["Transaction Date"].dtype

In [67]:
dp["Transaction Date"] = dp["Transaction Date"].fillna("Unknown")

In [68]:
dp.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [70]:
dp = dp.sort_values("Transaction ID")

In [71]:
dp.to_csv("cafe_sales_cleaned.csv", index=False)